lzc-sdk-version: "0.1"
name: Kurpod
package: xyz.mxue.app.kurpod
version: 0.0.2
description: 带有无辜文件名的加密文件容器
homepage: https://github.com/srv1n/kurpod
author: srv1n
application:
  subdomain: kurpod
  background_task: false
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://kurpod-server.xyz.mxue.app.kurpod.lzcapp:3000/
services:
  kurpod-server:
    image: registry.lazycat.cloud/mxuexxmy/srv1n/kurpod-server:a50d9c68abc2cfb2
    binds:
      - /lzcapp/var/data:/blobs
